import React from "react";
import { LegalLayout } from "@/components/LegalLayout";

export default function TermsPage() {
  return (
    <LegalLayout
      appName="Dreems"
      title="Dreems – Terms of Use"
      subtitle="Please read these terms carefully before using Dreems."
    >
      <p className="text-sm text-slate-300">
        <span className="font-medium">Last updated:</span> November 27, 2025
      </p>

      <p>
        Welcome to Dreems! By using the app, you agree to the following terms.
      </p>

      <h2>1. Eligibility</h2>
      <p>
        You must be <strong>18 or older</strong> to use the app. Children may
        enjoy stories created by adults, but the app is intended to be operated
        by parents and caregivers.
      </p>

      <h2>2. Purpose of the App</h2>
      <p>
        Dreems lets adults generate AI-powered children’s stories by providing
        prompts, preferences, and optional child details like name or age
        group. The app is for entertainment and educational storytelling
        purposes only.
      </p>

      <h2>3. User Content</h2>
      <p>
        You own the stories and content you create using Dreems. We do not
        claim ownership over your user-generated content.
      </p>
      <p>We do NOT:</p>
      <ul>
        <li>Publish your stories</li>
        <li>Sell your stories</li>
        <li>Share your stories with third parties</li>
      </ul>
      <p>
        We only process your input for the purpose of generating AI-powered
        stories and illustrations within the app.
      </p>

      <h2>4. AI Content</h2>
      <p>
        Stories and illustrations are generated by artificial intelligence and
        may sometimes contain errors, unexpected content, or inaccuracies.
      </p>
      <p>Do not rely on AI-generated content for:</p>
      <ul>
        <li>Medical or health-related advice</li>
        <li>Legal or financial advice</li>
        <li>Safety-critical decisions</li>
      </ul>

      <h2>5. Purchases</h2>
      <p>
        Dreems may offer in-app purchases such as story packs, token bundles, or
        premium content. All purchases are processed through{" "}
        <strong>Apple In-App Purchases</strong> or{" "}
        <strong>Google Play Billing</strong>, depending on your device.
      </p>
      <p>
        Pricing, taxes, and currency are determined by the platform. Refunds are
        handled according to Apple’s and Google’s respective policies and
        applicable local law.
      </p>

      <h2>6. Prohibited Uses</h2>
      <p>You agree not to use Dreems to:</p>
      <ul>
        <li>Abuse, harass, or harm others</li>
        <li>
          Create or distribute hateful, violent, explicit, or otherwise
          inappropriate content
        </li>
        <li>Reverse-engineer, decompile, or tamper with the app</li>
        <li>Interfere with servers, security, or network operations</li>
        <li>Violate any applicable laws or regulations</li>
      </ul>

      <h2>7. Termination</h2>
      <p>
        We may suspend or terminate your access to Dreems at any time if we
        reasonably believe you have violated these Terms of Use, engaged in
        fraudulent behavior, or if we are required to do so by law.
      </p>

      <h2>8. Disclaimer &amp; Limitation of Liability</h2>
      <p>
        Dreems is provided on an <strong>“as is”</strong> and{" "}
        <strong>“as available”</strong> basis, without any warranties of any
        kind, whether express or implied.
      </p>
      <p>We are not responsible for:</p>
      <ul>
        <li>Service interruptions or downtime</li>
        <li>Loss of data or content</li>
        <li>Errors or inaccuracies in AI-generated content</li>
      </ul>
      <p>
        To the fullest extent permitted by law, we are not liable for any
        indirect, incidental, or consequential damages arising from your use of
        the app.
      </p>

      <h2>9. Updates to These Terms</h2>
      <p>
        We may update these Terms of Use from time to time. When we do, we will
        update the “Last updated” date above. Your continued use of the app
        after changes are made means you accept the updated terms.
      </p>

      <h2>10. Contact</h2>
      <p>
        If you have any questions about these Terms of Use, you can contact us
        at:
      </p>
      <p>
        <strong>Email:</strong>{" "}
        <a
          href="mailto:support@barkingcode.com"
          className="text-sky-300 hover:text-sky-200"
        >
          support@barkingcode.com
        </a>
        <br />
        <strong>Website:</strong>{" "}
        <a
          href="https://barkingcode.com"
          target="_blank"
          rel="noreferrer"
          className="text-sky-300 hover:text-sky-200"
        >
          https://barkingcode.com
        </a>
      </p>
    </LegalLayout>
  );
}
